import { Language } from './translations';

/**
 * 법적 페이지, 보안 통계, Footer 등 추가 번역 텍스트
 */
export const extraTranslations: Record<Language, {
    // Footer
    footer: {
        privacy: string;
        terms: string;
        about: string;
        contact: string;
        rights: string;
        tagline: string;
    };
    // 보안 통계 섹션
    stats: {
        title: string;
        subtitle: string;
        items: { value: string; label: string }[];
    };
    // Privacy Policy
    privacy: {
        title: string;
        lastUpdated: string;
        sections: { heading: string; content: string }[];
    };
    // Terms of Service
    terms: {
        title: string;
        lastUpdated: string;
        sections: { heading: string; content: string }[];
    };
    // About
    about: {
        title: string;
        sections: { heading: string; content: string }[];
    };
}> = {
    en: {
        footer: {
            privacy: "Privacy Policy",
            terms: "Terms of Service",
            about: "About Us",
            contact: "Contact",
            rights: "All rights reserved.",
            tagline: "100% Secure Client-Side Password Generator — No Data Leaves Your Browser."
        },
        stats: {
            title: "Password Security by the Numbers",
            subtitle: "Why password strength really matters in today's digital world.",
            items: [
                { value: "80%", label: "of data breaches are caused by weak or reused passwords" },
                { value: "10B+", label: "passwords have been leaked in public data breaches" },
                { value: "< 1 sec", label: "to crack a 6-character password with brute force" },
                { value: "34K years", label: "to crack a 16-character mixed password" }
            ]
        },
        privacy: {
            title: "Privacy Policy",
            lastUpdated: "Last updated: February 2026",
            sections: [
                {
                    heading: "Introduction",
                    content: "Strong Password Generator (\"we\", \"us\", or \"our\") operates the password generator website. This page informs you of our policies regarding the collection, use, and disclosure of personal information when you use our Service."
                },
                {
                    heading: "Information We Collect",
                    content: "We do NOT collect any personal information. Our password generator runs entirely in your browser. No passwords, settings, or personal data are ever transmitted to our servers. We do not use cookies to track individual users."
                },
                {
                    heading: "Third-Party Services",
                    content: "We use Google AdSense to display advertisements. Google may use cookies and similar technologies to serve ads based on your prior visits to our website or other websites. You can opt out of personalized advertising by visiting Google's Ads Settings (https://adssettings.google.com)."
                },
                {
                    heading: "Analytics",
                    content: "We may use third-party analytics services (such as Google Analytics) to help us understand how users interact with our website. These services collect information such as how often users visit the site, what pages they visit, and what other sites they used prior to coming to our site. We use this information solely to improve our Service."
                },
                {
                    heading: "Changes to This Policy",
                    content: "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page with an updated date."
                },
                {
                    heading: "Contact Us",
                    content: "If you have any questions about this Privacy Policy, please contact us at: support@strongpassgen.com"
                }
            ]
        },
        terms: {
            title: "Terms of Service",
            lastUpdated: "Last updated: February 2026",
            sections: [
                {
                    heading: "Acceptance of Terms",
                    content: "By accessing and using Strong Password Generator, you accept and agree to be bound by the terms and provisions of this agreement."
                },
                {
                    heading: "Description of Service",
                    content: "Strong Password Generator provides a free, client-side tool for generating random passwords. The service is provided \"as is\" without warranties of any kind, either express or implied."
                },
                {
                    heading: "User Responsibilities",
                    content: "You are solely responsible for safeguarding and managing the passwords generated by this tool. We are not responsible for any losses or damages arising from your failure to protect your passwords."
                },
                {
                    heading: "Intellectual Property",
                    content: "The content, design, and code of this website are protected by copyright law. You may not reproduce, distribute, or create derivative works without prior written consent."
                },
                {
                    heading: "Limitation of Liability",
                    content: "In no event shall Strong Password Generator be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service."
                },
                {
                    heading: "Changes to Terms",
                    content: "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms."
                }
            ]
        },
        about: {
            title: "About Strong Password Generator",
            sections: [
                {
                    heading: "Our Mission",
                    content: "We believe everyone deserves access to strong, secure passwords — for free. Our mission is to make online security simple, accessible, and trustworthy for people around the world."
                },
                {
                    heading: "How It Works",
                    content: "Our password generator uses the Web Crypto API (crypto.getRandomValues), a cryptographically secure random number generator built into your browser. This means your passwords are generated locally on your device — nothing is ever sent over the internet."
                },
                {
                    heading: "Why Trust Us?",
                    content: "Unlike many password tools, our entire codebase runs in the browser. There is no backend server, no database, and no way for us to see or store your passwords. This architecture ensures maximum privacy and security by design."
                },
                {
                    heading: "Contact",
                    content: "Have questions, feedback, or partnership inquiries? Reach out to us at: support@strongpassgen.com"
                }
            ]
        }
    },
    ko: {
        footer: {
            privacy: "개인정보처리방침",
            terms: "이용약관",
            about: "소개",
            contact: "문의하기",
            rights: "All rights reserved.",
            tagline: "100% 안전한 클라이언트 사이드 비밀번호 생성기 — 데이터는 브라우저를 떠나지 않습니다."
        },
        stats: {
            title: "숫자로 보는 비밀번호 보안",
            subtitle: "오늘날 디지털 세계에서 비밀번호 강도가 왜 중요한지 알아보세요.",
            items: [
                { value: "80%", label: "의 데이터 유출은 약하거나 재사용된 비밀번호가 원인입니다" },
                { value: "100억+", label: "개의 비밀번호가 공개 데이터 유출로 노출되었습니다" },
                { value: "< 1초", label: "만에 6자리 비밀번호가 무차별 대입 공격으로 해킹됩니다" },
                { value: "3만 4천 년", label: "이 걸려야 16자리 혼합 비밀번호를 해킹할 수 있습니다" }
            ]
        },
        privacy: {
            title: "개인정보처리방침",
            lastUpdated: "최종 업데이트: 2026년 2월",
            sections: [
                {
                    heading: "소개",
                    content: "강력한 비밀번호 생성기(이하 \"당사\")는 비밀번호 생성기 웹사이트를 운영합니다. 이 페이지는 서비스 이용 시 개인정보의 수집, 사용 및 공개에 관한 당사의 정책을 안내합니다."
                },
                {
                    heading: "수집하는 정보",
                    content: "당사는 어떠한 개인정보도 수집하지 않습니다. 비밀번호 생성기는 전적으로 사용자의 브라우저에서 실행됩니다. 비밀번호, 설정 또는 개인 데이터가 서버로 전송되지 않습니다. 개별 사용자를 추적하기 위한 쿠키를 사용하지 않습니다."
                },
                {
                    heading: "서드파티 서비스",
                    content: "당사는 광고 게재를 위해 Google 애드센스를 사용합니다. Google은 이전 웹사이트 방문 기록을 기반으로 광고를 게재하기 위해 쿠키 및 유사 기술을 사용할 수 있습니다. Google의 광고 설정(https://adssettings.google.com)에서 맞춤 광고를 해제할 수 있습니다."
                },
                {
                    heading: "분석 도구",
                    content: "당사는 사용자가 웹사이트와 어떻게 상호작용하는지 이해하기 위해 Google Analytics와 같은 서드파티 분석 서비스를 사용할 수 있습니다. 이 정보는 서비스 개선을 위해서만 사용됩니다."
                },
                {
                    heading: "정책 변경",
                    content: "당사는 수시로 개인정보처리방침을 업데이트할 수 있습니다. 변경 사항은 업데이트된 날짜와 함께 이 페이지에 게시됩니다."
                },
                {
                    heading: "문의",
                    content: "개인정보처리방침에 관한 질문이 있으시면 support@strongpassgen.com으로 연락해 주세요."
                }
            ]
        },
        terms: {
            title: "이용약관",
            lastUpdated: "최종 업데이트: 2026년 2월",
            sections: [
                {
                    heading: "약관 동의",
                    content: "강력한 비밀번호 생성기에 접속하고 사용함으로써 본 약관의 조건에 동의하게 됩니다."
                },
                {
                    heading: "서비스 설명",
                    content: "강력한 비밀번호 생성기는 무작위 비밀번호를 생성하는 무료 클라이언트 사이드 도구를 제공합니다. 서비스는 명시적이든 묵시적이든 어떠한 종류의 보증 없이 \"있는 그대로\" 제공됩니다."
                },
                {
                    heading: "사용자 책임",
                    content: "이 도구로 생성된 비밀번호의 보관 및 관리는 전적으로 사용자의 책임입니다. 비밀번호 보호 실패로 인한 손실이나 손해에 대해 당사는 책임을 지지 않습니다."
                },
                {
                    heading: "지적 재산권",
                    content: "이 웹사이트의 콘텐츠, 디자인 및 코드는 저작권법에 의해 보호됩니다. 사전 서면 동의 없이 복제, 배포 또는 2차 저작물을 만들 수 없습니다."
                },
                {
                    heading: "책임 제한",
                    content: "어떠한 경우에도 강력한 비밀번호 생성기는 서비스 사용으로 인한 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임을 지지 않습니다."
                },
                {
                    heading: "약관 변경",
                    content: "당사는 언제든지 본 약관을 수정할 권리를 가집니다. 변경 후 서비스를 계속 사용하면 새로운 약관에 동의한 것으로 간주됩니다."
                }
            ]
        },
        about: {
            title: "강력한 비밀번호 생성기 소개",
            sections: [
                {
                    heading: "우리의 미션",
                    content: "모든 사람이 강력하고 안전한 비밀번호를 무료로 이용할 수 있어야 한다고 믿습니다. 우리의 사명은 전 세계 사람들이 온라인 보안을 간단하고, 접근 가능하며, 신뢰할 수 있도록 만드는 것입니다."
                },
                {
                    heading: "작동 원리",
                    content: "저희 비밀번호 생성기는 브라우저에 내장된 암호학적으로 안전한 난수 생성기인 Web Crypto API(crypto.getRandomValues)를 사용합니다. 즉, 비밀번호가 사용자의 기기에서 로컬로 생성되며 인터넷을 통해 전송되지 않습니다."
                },
                {
                    heading: "왜 신뢰할 수 있나요?",
                    content: "많은 비밀번호 도구와 달리, 저희의 전체 코드베이스는 브라우저에서 실행됩니다. 백엔드 서버도, 데이터베이스도 없으며, 비밀번호를 보거나 저장할 방법이 없습니다. 이 아키텍처는 설계상 최대의 개인정보 보호와 보안을 보장합니다."
                },
                {
                    heading: "연락처",
                    content: "질문, 피드백 또는 파트너십 문의가 있으시면 support@strongpassgen.com으로 연락해 주세요."
                }
            ]
        }
    },
    es: {
        footer: {
            privacy: "Política de Privacidad",
            terms: "Términos de Servicio",
            about: "Sobre Nosotros",
            contact: "Contacto",
            rights: "Todos los derechos reservados.",
            tagline: "Generador de contraseñas 100% seguro del lado del cliente — Ningún dato sale de tu navegador."
        },
        stats: {
            title: "Seguridad de Contraseñas en Números",
            subtitle: "Por qué la fortaleza de las contraseñas realmente importa en el mundo digital actual.",
            items: [
                { value: "80%", label: "de las violaciones de datos son causadas por contraseñas débiles o reutilizadas" },
                { value: "10B+", label: "contraseñas han sido filtradas en violaciones de datos públicas" },
                { value: "< 1 seg", label: "para descifrar una contraseña de 6 caracteres con fuerza bruta" },
                { value: "34K años", label: "para descifrar una contraseña mixta de 16 caracteres" }
            ]
        },
        privacy: {
            title: "Política de Privacidad",
            lastUpdated: "Última actualización: Febrero 2026",
            sections: [
                {
                    heading: "Introducción",
                    content: "Strong Password Generator (\"nosotros\") opera el sitio web del generador de contraseñas. Esta página te informa sobre nuestras políticas con respecto a la recopilación, uso y divulgación de información personal cuando utilizas nuestro Servicio."
                },
                {
                    heading: "Información que Recopilamos",
                    content: "NO recopilamos ninguna información personal. Nuestro generador de contraseñas funciona completamente en tu navegador. Ninguna contraseña, configuración o dato personal se transmite a nuestros servidores. No usamos cookies para rastrear usuarios individuales."
                },
                {
                    heading: "Servicios de Terceros",
                    content: "Usamos Google AdSense para mostrar anuncios. Google puede usar cookies y tecnologías similares para servir anuncios basados en tus visitas previas. Puedes optar por no recibir publicidad personalizada visitando la Configuración de Anuncios de Google (https://adssettings.google.com)."
                },
                {
                    heading: "Analíticas",
                    content: "Podemos usar servicios de análisis de terceros (como Google Analytics) para entender cómo los usuarios interactúan con nuestro sitio web. Esta información se utiliza únicamente para mejorar nuestro Servicio."
                },
                {
                    heading: "Cambios en esta Política",
                    content: "Podemos actualizar nuestra Política de Privacidad periódicamente. Te notificaremos de cualquier cambio publicando la nueva Política de Privacidad en esta página con una fecha actualizada."
                },
                {
                    heading: "Contáctanos",
                    content: "Si tienes alguna pregunta sobre esta Política de Privacidad, contáctanos en: support@strongpassgen.com"
                }
            ]
        },
        terms: {
            title: "Términos de Servicio",
            lastUpdated: "Última actualización: Febrero 2026",
            sections: [
                {
                    heading: "Aceptación de Términos",
                    content: "Al acceder y utilizar Strong Password Generator, aceptas y te comprometes a cumplir con los términos y disposiciones de este acuerdo."
                },
                {
                    heading: "Descripción del Servicio",
                    content: "Strong Password Generator proporciona una herramienta gratuita del lado del cliente para generar contraseñas aleatorias. El servicio se proporciona \"tal cual\" sin garantías de ningún tipo."
                },
                {
                    heading: "Responsabilidades del Usuario",
                    content: "Eres el único responsable de proteger y gestionar las contraseñas generadas por esta herramienta. No somos responsables de ninguna pérdida o daño derivado de tu falta de protección de tus contraseñas."
                },
                {
                    heading: "Propiedad Intelectual",
                    content: "El contenido, diseño y código de este sitio web están protegidos por la ley de derechos de autor. No puedes reproducir, distribuir o crear obras derivadas sin consentimiento previo por escrito."
                },
                {
                    heading: "Limitación de Responsabilidad",
                    content: "En ningún caso Strong Password Generator será responsable de ningún daño indirecto, incidental, especial, consecuente o punitivo resultante de tu uso del servicio."
                },
                {
                    heading: "Cambios en los Términos",
                    content: "Nos reservamos el derecho de modificar estos términos en cualquier momento. El uso continuado del servicio después de los cambios constituye la aceptación de los nuevos términos."
                }
            ]
        },
        about: {
            title: "Sobre Strong Password Generator",
            sections: [
                {
                    heading: "Nuestra Misión",
                    content: "Creemos que todos merecen acceso a contraseñas fuertes y seguras, de forma gratuita. Nuestra misión es hacer que la seguridad en línea sea simple, accesible y confiable para personas de todo el mundo."
                },
                {
                    heading: "Cómo Funciona",
                    content: "Nuestro generador de contraseñas utiliza la Web Crypto API (crypto.getRandomValues), un generador de números aleatorios criptográficamente seguro integrado en tu navegador. Esto significa que tus contraseñas se generan localmente en tu dispositivo."
                },
                {
                    heading: "¿Por qué Confiar en Nosotros?",
                    content: "A diferencia de muchas herramientas de contraseñas, todo nuestro código se ejecuta en el navegador. No hay servidor backend, ni base de datos, ni forma de que veamos o almacenemos tus contraseñas. Esta arquitectura garantiza la máxima privacidad y seguridad por diseño."
                },
                {
                    heading: "Contacto",
                    content: "¿Tienes preguntas, comentarios o consultas de asociación? Contáctanos en: support@strongpassgen.com"
                }
            ]
        }
    }
};
